import { Finding, RiskLevel } from '../types';

export const getRiskColor = (risk: RiskLevel): string => {
  switch (risk) {
    case 'high':
      return 'bg-red-600 text-white';
    case 'medium':
      return 'bg-amber-500 text-white';
    case 'low':
      return 'bg-blue-500 text-white';
    case 'none':
      return 'bg-green-500 text-white';
    default:
      return 'bg-gray-200 text-gray-800';
  }
};

export const getRiskBorderColor = (risk: RiskLevel): string => {
  switch (risk) {
    case 'high':
      return 'border-red-600';
    case 'medium':
      return 'border-amber-500';
    case 'low':
      return 'border-blue-500';
    case 'none':
      return 'border-green-500';
    default:
      return 'border-gray-200';
  }
};

export const getRiskTextColor = (risk: RiskLevel): string => {
  switch (risk) {
    case 'high':
      return 'text-red-600';
    case 'medium':
      return 'text-amber-500';
    case 'low':
      return 'text-blue-500';
    case 'none':
      return 'text-green-500';
    default:
      return 'text-gray-500';
  }
};

export const countFindingsByRisk = (findings: Finding[]): Record<RiskLevel, number> => {
  const counts: Record<RiskLevel, number> = {
    high: 0,
    medium: 0,
    low: 0,
    none: 0
  };
  
  findings.forEach(finding => {
    counts[finding.riskLevel]++;
  });
  
  return counts;
};

export const getRiskLevelLabel = (risk: RiskLevel): string => {
  switch (risk) {
    case 'high':
      return 'risk_level_high';
    case 'medium':
      return 'risk_level_medium';
    case 'low':
      return 'risk_level_low';
    case 'none':
      return 'risk_level_none';
    default:
      return 'risk_level_unknown';
  }
};

export const getCategoryLabel = (category: string): string => {
  // Normalize category string to a consistent snake_case format for translation keys
  // This handles cases like "data-protection" -> "data_protection" and "Contract Formation" -> "contract_formation"
  const normalizedCategory = category.toLowerCase().replace(/[-\s]/g, '_');

  switch (normalizedCategory) {
    case 'compliance':
      return 'category_compliance';
    case 'risk':
      return 'category_risk';
    case 'data_protection':
      return 'category_data_protection';
    case 'enforceability':
      return 'category_enforceability';
    case 'drafting':
      return 'category_drafting';
    case 'commercial':
      return 'category_commercial';
    case 'contract_formation':
      return 'category_contract_formation';
    case 'risk_allocation':
      return 'category_risk_allocation';
    case 'insurance':
      return 'category_insurance';
    case 'intellectual_property':
      return 'category_intellectual_property';
    case 'pension_retirement':
      return 'category_pension_retirement';
    // ADDED: New categories from user feedback
    case 'contract_terms':
      return 'category_contract_terms';
    case 'regulatory_compliance':
      return 'category_regulatory_compliance';
    case 'liability':
      return 'category_liability';
    case 'tenant_rights':
      return 'category_tenant_rights';
    case 'financial_terms':
      return 'category_financial_terms';
    case 'termination':
      return 'category_termination';
    case 'property_condition':
      return 'category_property_condition';
    case 'property_management':
      return 'category_property_management';
    case 'property_rights':
      return 'category_property_rights';
    case 'personnel':
      return 'category_personnel';
    case 'legal_compliance':
      return 'category_legal_compliance';
    case 'financial':
      return 'category_financial';
    case 'indemnification':
      return 'category_indemnification';
    case 'consumer_protection':
      return 'category_consumer_protection';
    case 'payment_terms':
      return 'category_payment_terms';
    case 'force_majeure':
      return 'category_force_majeure';
    case 'performance_standards':
      return 'category_performance_standards';
    case 'discrimination':
      return 'category_discrimination';
    case 'legal_enforceability':
      return 'category_legal_enforceability';
    case 'pricing':
      return 'category_pricing';
    default:
      // Fallback for any other category generated by the LLM
      // Ensures a consistent key format even for unexpected categories
      return `category_${normalizedCategory}`;
  }
};